### ISSUE TITLE
Deps are wrong

### ISSUE THREAD

**Issue by tristanbes** [auth0/jwt-auth-bundle#16]
Either the bundle has depandancies (or even dev-depandancies), and in that case those depandancies should go in the `composer.json`

But in the installation process you can't say install this bundle by adding the bundle itself and another library (https://github.com/auth0/jwt-auth-bundle/blame/master/README.md#L43) `"adoy/oauth2": "dev-master",`

**Comment by glena** [comment]
I think this is out of date. 
Previouslt `adoy/oauth2` didnt have ant update tag so point to `dev-master` was needed (they tag a new release recently after a PR I send). Since `dev-master` is not `stable` it is easier to add it manually than making the users change the min stability requirements of their project.

I will update the readme, thanks

**Comment by adrienbrault** [comment]
Can you require a tagged version of that dependency ? There are tags: https://github.com/adoy/PHP-OAuth2/releases

**Comment by glena** [comment]
You are right, I am releasing a new revision with this fix. thx
